blank_issues_enabled: false
contact_links:
  - name: Microsoft Security Policy
    url: https://github.com/MicrosoftDocs/Contribute/security/policy
    about: Read about and report security vulnerabilities here.
